name: airjordan
channels:
  - defaults
dependencies:
  - ipykernel=5.3.4
  - pip=20.2.4
  - python=3.7.9
  - pip:
    - apache-airflow==2.0.0
    - beautifulsoup4==4.9.3
    - catboost==0.24.4
    - ohmysportsfeedspy==2.1.0
    - psycopg2-binary==2.8.6
    - python-dotenv==0.15.0
    - simplejson==3.17.2
    - tqdm==4.56.2