name: airjordan
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - ld_impl_linux-64=2.35.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.2.4
  - python=3.7.9
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - alembic==1.5.4
    - apache-airflow==2.0.0
    - apache-airflow-providers-ftp==1.0.0
    - apache-airflow-providers-http==1.0.0
    - apache-airflow-providers-imap==1.0.0
    - apache-airflow-providers-sqlite==1.0.0
    - apispec==3.3.2
    - argcomplete==1.12.2
    - attrs==20.3.0
    - babel==2.9.0
    - beautifulsoup4==4.9.3
    - cached-property==1.5.2
    - cattrs==1.2.0
    - cffi==1.14.4
    - chardet==3.0.4
    - click==7.1.2
    - clickclick==20.10.2
    - colorama==0.4.4
    - colorlog==4.0.2
    - commonmark==0.9.1
    - connexion==2.7.0
    - croniter==0.3.37
    - cryptography==3.4.1
    - defusedxml==0.6.0
    - dill==0.3.3
    - dnspython==2.1.0
    - docutils==0.16
    - email-validator==1.1.2
    - flask==1.1.2
    - flask-appbuilder==3.1.1
    - flask-babel==1.0.0
    - flask-caching==1.9.0
    - flask-jwt-extended==3.25.0
    - flask-login==0.4.1
    - flask-openid==1.2.5
    - flask-sqlalchemy==2.4.4
    - flask-swagger==0.2.13
    - flask-wtf==0.14.3
    - funcsigs==1.0.2
    - gunicorn==19.10.0
    - idna==2.10
    - importlib-metadata==1.7.0
    - importlib-resources==1.5.0
    - inflection==0.5.1
    - iso8601==0.1.14
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - json-merge-patch==0.2
    - jsonschema==3.2.0
    - lazy-object-proxy==1.4.3
    - lockfile==0.12.2
    - mako==1.1.4
    - markdown==3.3.3
    - markupsafe==1.1.1
    - marshmallow==3.10.0
    - marshmallow-enum==1.5.1
    - marshmallow-oneofschema==2.1.0
    - marshmallow-sqlalchemy==0.23.1
    - natsort==7.1.1
    - numpy==1.20.1
    - openapi-spec-validator==0.2.9
    - pandas==1.2.1
    - pendulum==2.1.2
    - prison==0.1.3
    - psutil==5.8.0
    - pycparser==2.20
    - pygments==2.7.4
    - pyjwt==2.0.1
    - pyrsistent==0.17.3
    - python-daemon==2.2.4
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - python-graphviz==0.16
    - python-nvd3==0.15.0
    - python-slugify==4.0.1
    - python3-openid==3.2.0
    - pytz==2021.1
    - pytzdata==2020.1
    - pyyaml==5.4.1
    - requests==2.23.0
    - rich==9.2.0
    - semantic-version==2.8.5
    - setproctitle==1.2.2
    - setuptools-rust==0.11.6
    - six==1.15.0
    - soupsieve==2.1
    - sqlalchemy==1.3.23
    - sqlalchemy-jsonfield==1.0.0
    - sqlalchemy-utils==0.36.8
    - swagger-ui-bundle==0.0.8
    - tabulate==0.8.7
    - tenacity==6.2.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - thrift==0.13.0
    - toml==0.10.2
    - typing-extensions==3.7.4.3
    - tzlocal==1.5.1
    - unicodecsv==0.14.1
    - urllib3==1.25.11
    - werkzeug==1.0.1
    - wtforms==2.3.3
    - zipp==3.4.0
