CREATE TABLE public.player_gamelogs
(
    game_id bigint,
    game_starttime timestamp with time zone,
    game_awayteamabbreviation text COLLATE pg_catalog."default",
    game_hometeamabbreviation text COLLATE pg_catalog."default",
    player_id bigint,
    player_firstname text COLLATE pg_catalog."default",
    player_lastname text COLLATE pg_catalog."default",
    player_position text COLLATE pg_catalog."default",
    player_jerseynumber double precision,
    team_id bigint,
    team_abbreviation text COLLATE pg_catalog."default",
    stats_fieldgoals_fg2ptatt bigint,
    stats_fieldgoals_fg2ptattpergame double precision,
    stats_fieldgoals_fg2ptmade bigint,
    stats_fieldgoals_fg2ptmadepergame double precision,
    stats_fieldgoals_fg2ptpct double precision,
    stats_fieldgoals_fg3ptatt bigint,
    stats_fieldgoals_fg3ptattpergame double precision,
    stats_fieldgoals_fg3ptmade bigint,
    stats_fieldgoals_fg3ptmadepergame double precision,
    stats_fieldgoals_fg3ptpct double precision,
    stats_fieldgoals_fgatt bigint,
    stats_fieldgoals_fgattpergame double precision,
    stats_fieldgoals_fgmade bigint,
    stats_fieldgoals_fgmadepergame double precision,
    stats_fieldgoals_fgpct double precision,
    stats_freethrows_ftatt bigint,
    stats_freethrows_ftattpergame double precision,
    stats_freethrows_ftmade bigint,
    stats_freethrows_ftmadepergame double precision,
    stats_freethrows_ftpct double precision,
    stats_rebounds_offreb bigint,
    stats_rebounds_offrebpergame double precision,
    stats_rebounds_defreb bigint,
    stats_rebounds_defrebpergame double precision,
    stats_rebounds_reb bigint,
    stats_rebounds_rebpergame double precision,
    stats_offense_ast bigint,
    stats_offense_astpergame double precision,
    stats_offense_pts bigint,
    stats_offense_ptspergame double precision,
    stats_defense_tov bigint,
    stats_defense_tovpergame double precision,
    stats_defense_stl bigint,
    stats_defense_stlpergame double precision,
    stats_defense_blk bigint,
    stats_defense_blkpergame double precision,
    stats_defense_blkagainst bigint,
    stats_defense_blkagainstpergame double precision,
    stats_miscellaneous_fouls bigint,
    stats_miscellaneous_foulspergame double precision,
    stats_miscellaneous_foulsdrawn bigint,
    stats_miscellaneous_foulsdrawnpergame double precision,
    stats_miscellaneous_foulpers bigint,
    stats_miscellaneous_foulperspergame double precision,
    stats_miscellaneous_foulpersdrawn bigint,
    stats_miscellaneous_foulpersdrawnpergame double precision,
    stats_miscellaneous_foultech bigint,
    stats_miscellaneous_foultechpergame double precision,
    stats_miscellaneous_foultechdrawn bigint,
    stats_miscellaneous_foultechdrawnpergame double precision,
    stats_miscellaneous_foulflag1 bigint,
    stats_miscellaneous_foulflag1pergame double precision,
    stats_miscellaneous_foulflag1drawn bigint,
    stats_miscellaneous_foulflag1drawnpergame double precision,
    stats_miscellaneous_foulflag2 bigint,
    stats_miscellaneous_foulflag2pergame double precision,
    stats_miscellaneous_foulflag2drawn bigint,
    stats_miscellaneous_foulflag2drawnpergame double precision,
    stats_miscellaneous_ejections bigint,
    stats_miscellaneous_plusminus bigint,
    stats_miscellaneous_plusminuspergame double precision,
    stats_miscellaneous_minseconds bigint,
    stats_miscellaneous_minsecondspergame double precision,
    stats_miscellaneous_gamesstarted bigint
);