CREATE TABLE IF NOT EXISTS public.games
(
    season text,
    id bigint,
    startTime timestamp with time zone,
    endedTime timestamp with time zone,
    awayTeam_id bigint,
    awayTeam_abbreviation text,
    homeTeam_id bigint,
    homeTeam_abbreviation text,
    venue_id bigint,
    venue_name text,
    venueAllegiance text,
    scheduleStatus text,
    originalStartTime timestamp with time zone,
    delayedOrPostponedReason text,
    playedStatus text,
    attendance bigint,
    weather_type text,
    weather_description text,
    weather_wind_speed_milesPerHour bigint,
    weather_wind_speed_kilometersPerHour bigint,
    weather_wind_direction_degrees bigint,
    weather_wind_direction_label text,
    weather_temperature_fahrenheit bigint,
    weather_temperature_celsius bigint,
    weather_precipitation_type text,
    weather_precipitation_percent text,
    weather_precipitation_amount_millimeters double precision,
    weather_precipitation_amount_centimeters text,
    weather_precipitation_amount_inches text,
    weather_precipitation_amount_feet text,
    weather_humidityPercent bigint,
    currentQuarter text,
    currentQuarterSecondsRemaining text,
    currentIntermission text,
    awayScoreTotal bigint,
    homeScoreTotal bigint,
    quarters jsonb,
    officials jsonb,
    broadcasters jsonb
);