create table if not exists public.players
(
    id bigint,
    firstName text,
    lastName text,
    primaryPosition text,
    jerseyNumber bigint,
    currentTeam_id bigint,
    currentTeam_abbreviation text,
    currentRosterStatus text,
    height text,
    weight bigint,
    birthDate date,
    age bigint,
    birthCity text,
    birthCountry text,
    rookie bool,
    highSchool text,
    college text,
    handedness_shoots text,
    officialImageSrc text,
    currentContractYear bigint,
    drafted_year bigint,
    drafted_team_id bigint,
    drafted_team_abbreviation text,
    drafted_pickTeam_id bigint,
    drafted_pickTeam_abbreviation text,
    drafted_round bigint,
    drafted_roundPick bigint,
    drafted_overallPick bigint,
    currentInjury_description text,
    currentInjury_playingProbability text,
    externalMappings json,
    socialMediaAccounts json
);